target_compile_definitions(${PROJECT_NAME} PRIVATE
    SAMPLE_RATE=48000
    I2S_AUDIO_ENABLED=1
    I2S_TEST_SINE=0
    WS2812_ENABLED=0
    MIDI_IN_ENABLED=0
    MIDI_RESET_EVERY_BEAT=16
    MIDI_CLOCK_MULTIPLIER=2
    MIDI_NOTE_KEY=0
    PCB_V2_LAYOUT=0
)